-- 베이스 스키마(진행자용 템플릿은 각 사용자 스키마 내에서 생성)
CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(100) NOT NULL,
  email       VARCHAR2(200) UNIQUE,
  phone       VARCHAR2(40),
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE orders (
  order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  NUMBER NOT NULL REFERENCES customers(customer_id),
  order_date   DATE   DEFAULT SYSDATE,
  status       VARCHAR2(20) CHECK (status IN ('NEW','PAID','SHIPPED','CANCELLED'))
);

CREATE TABLE order_items (
  order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      NUMBER NOT NULL REFERENCES orders(order_id),
  product_sku   VARCHAR2(40) NOT NULL,
  qty           NUMBER CHECK (qty>0),
  unit_price    NUMBER(10,2) CHECK (unit_price>=0)
);

INSERT INTO customers(name,email,phone) VALUES ('Alice','alice@example.com','010-1111-1111');
INSERT INTO customers(name,email,phone) VALUES ('Bob','bob@example.com','010-2222-2222');
INSERT INTO orders(customer_id,status) VALUES (1,'NEW');
INSERT INTO orders(customer_id,status) VALUES (2,'PAID');
INSERT INTO order_items(order_id,product_sku,qty,unit_price) VALUES (1,'SKU-100',2,19.99);
INSERT INTO order_items(order_id,product_sku,qty,unit_price) VALUES (1,'SKU-200',1,49.00);
INSERT INTO order_items(order_id,product_sku,qty,unit_price) VALUES (2,'SKU-300',3,9.90);
COMMIT;

CREATE or replace JSON RELATIONAL DUALITY VIEW orders_dv AS
  customers @insert @update @delete 
    {
      _id        : customer_id,
      name       : name,
      email      : email,
      phone      : phone,
      created_at : created_at,
      orders : orders @insert @update @delete 
        {
          _id       : order_id,
          orderDate : order_date,
          status    : status,
          items : order_items @insert @update @delete 
            {
              _id       : order_item_id,
              sku       : product_sku,
              quantity  : qty,
              unitPrice : unit_price
            }
        }
    };
